# This file was generated by Ansible for {{ ansible_fqdn }}
# Do NOT modify this file by hand!

from sentry.conf.server import *

import os.path

# Directories
CONF_ROOT = os.path.dirname(__file__)
STATIC_ROOT = '{{sentry_home}}/_static'

# Optimization
SENTRY_USE_BIG_INTS = True
SENTRY_SINGLE_ORGANIZATION = {{sentry_single_organization and 'True' or 'False'}}
SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'
SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'
SENTRY_DIGESTS = 'sentry.digests.backends.redis.RedisBackend'

# Setup database
DATABASES = {
    'default': {
        'ENGINE': '{{sentry_db_engine}}',
        'NAME': '{{sentry_db_name}}',
        'USER': '{{sentry_db_user}}',
        'PASSWORD': '{{sentry_db_password}}',
        {% if sentry_db_host %}'HOST': '{{sentry_db_host}}',{% endif %}
        {% if sentry_db_port %}'PORT': '{{sentry_db_port}}',{% endif %}
        'OPTIONS': {{sentry_db_options|to_nice_json}}
    }
}



SENTRY_ADMIN_EMAIL = '{{sentry_admins[0].email}}'

# A primary cache is required for things such as processing events
SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

{% if sentry_cache_backend and sentry_cache_location %}
CACHES = {
    'default': {
        'BACKEND': '{{sentry_cache_backend}}',
        'LOCATION': '{{sentry_cache_location}}',
    }
}
{% endif %}

{% if sentry_broker_url %}
CELERY_ALWAYS_EAGER = False
BROKER_URL = '{{sentry_broker_url}}'
{% endif %}

{% if sentry_buffer %}
SENTRY_BUFFER = '{{sentry_buffer}}'
SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'
{% endif %}

# If you're using a reverse proxy, you should enable the X-Forwarded-Proto
# and X-Forwarded-Host headers, and uncomment the following settings
{% if sentry_ssl %}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
{% endif %}

SENTRY_WEB_HOST = '{{sentry_web_host}}'
SENTRY_WEB_PORT = {{sentry_web_port}}
SENTRY_WEB_OPTIONS = {{sentry_web_options|to_nice_json}}

# Filestore
SENTRY_FILESTORE = 'django.core.files.storage.FileSystemStorage'
SENTRY_FILESTORE_OPTIONS = {
    'location': '{{sentry_home}}/_files'
}

{% if not sentry_auth_register %}
SENTRY_FEATURES['auth:register'] = False
{% endif %}

{% if sentry_beacon %}
SENTRY_BEACON = True
{% endif %}

TWITTER_CONSUMER_KEY = '{{sentry_twitter_consumer_key}}'
TWITTER_CONSUMER_SECRET = '{{sentry_twitter_consumer_secret}}'
FACEBOOK_APP_ID = '{{sentry_facebook_app_id}}'
FACEBOOK_API_SECRET = '{{sentry_facebook_api_secret}}'
GOOGLE_OAUTH2_CLIENT_ID = '{{sentry_google_oauth2_client_id}}'
GOOGLE_OAUTH2_CLIENT_SECRET = '{{sentry_google_oauth2_client_secret}}'
GITHUB_APP_ID = '{{sentry_github_app_id}}'
GITHUB_API_SECRET = '{{sentry_github_api_secret}}'
GITHUB_EXTENDED_PERMISSIONS = ['repo']
TRELLO_API_KEY = '{{sentry_trello_api_key}}'
TRELLO_API_SECRET = '{{sentry_trello_api_secret}}'
BITBUCKET_CONSUMER_KEY = '{{sentry_bitbucket_consumer_key}}'
BITBUCKET_CONSUMER_SECRET = '{{sentry_bitbucket_consumer_secret}}'

# Additional settings
{% for option in sentry_config_additional or [] %}
{{option}}
{% endfor %}
